FROM httpd:2.4
MAINTAINER z0nam <dr.strangelove@kberi.re.kr>

RUN apt-get update
RUN apt -y install software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt-get update
RUN apt -y install php7.4
COPY . /usr/local/apache2/htdocs
EXPOSE 80
